/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const DailyMealOrder = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'deliveryAddress' : IDL.Text,
  'userId' : IDL.Principal,
  'date' : Time,
  'skip' : IDL.Bool,
  'deliveryTime' : IDL.Nat,
  'selectedMeals' : IDL.Vec(IDL.Nat),
});
export const Meal = IDL.Record({
  'id' : IDL.Nat,
  'fat' : IDL.Nat,
  'carbs' : IDL.Nat,
  'calories' : IDL.Nat,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'nutritionistApproved' : IDL.Bool,
  'allergens' : IDL.Vec(IDL.Text),
  'protein' : IDL.Nat,
});
export const PaymentRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'method' : IDL.Text,
  'userId' : IDL.Principal,
  'date' : Time,
  'subscriptionPlan' : IDL.Text,
  'amount' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Subscription = IDL.Record({
  'status' : IDL.Text,
  'userId' : IDL.Principal,
  'plan' : IDL.Text,
  'isActive' : IDL.Bool,
  'billingCycle' : IDL.Text,
  'startDate' : Time,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'weight' : IDL.Float64,
  'height' : IDL.Float64,
  'activityLevel' : IDL.Text,
  'fitnessGoal' : IDL.Text,
  'dietaryPreferences' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'isOnboardingCompleted' : IDL.Bool,
  'gender' : IDL.Text,
  'allergies' : IDL.Vec(IDL.Text),
});
export const ProgressEntry = IDL.Record({
  'value' : IDL.Float64,
  'date' : Time,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'notificationType' : IDL.Text,
  'read' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDailyOrder' : IDL.Func([DailyMealOrder], [IDL.Nat], []),
  'addMeal' : IDL.Func([Meal], [IDL.Nat], []),
  'addPaymentRecord' : IDL.Func([PaymentRecord], [IDL.Nat], []),
  'addProgressEntry' : IDL.Func([IDL.Float64], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMeal' : IDL.Func([IDL.Nat], [], []),
  'getAllMeals' : IDL.Func([], [IDL.Vec(Meal)], ['query']),
  'getCallerSubscription' : IDL.Func([], [IDL.Opt(Subscription)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyOrder' : IDL.Func([IDL.Nat], [IDL.Opt(DailyMealOrder)], ['query']),
  'getMeal' : IDL.Func([IDL.Nat], [IDL.Opt(Meal)], ['query']),
  'getOrdersByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DailyMealOrder)],
      ['query'],
    ),
  'getPaymentsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PaymentRecord)],
      ['query'],
    ),
  'getProgressEntries' : IDL.Func([], [IDL.Vec(ProgressEntry)], ['query']),
  'getUserId' : IDL.Func([], [IDL.Principal], ['query']),
  'getUserNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSubscription' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(Subscription)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
  'saveCallerSubscription' : IDL.Func([Subscription], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendNotification' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text], [], []),
  'updateDailyOrder' : IDL.Func([IDL.Nat, DailyMealOrder], [], []),
  'updateMeal' : IDL.Func([IDL.Nat, Meal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const DailyMealOrder = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'deliveryAddress' : IDL.Text,
    'userId' : IDL.Principal,
    'date' : Time,
    'skip' : IDL.Bool,
    'deliveryTime' : IDL.Nat,
    'selectedMeals' : IDL.Vec(IDL.Nat),
  });
  const Meal = IDL.Record({
    'id' : IDL.Nat,
    'fat' : IDL.Nat,
    'carbs' : IDL.Nat,
    'calories' : IDL.Nat,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'nutritionistApproved' : IDL.Bool,
    'allergens' : IDL.Vec(IDL.Text),
    'protein' : IDL.Nat,
  });
  const PaymentRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'method' : IDL.Text,
    'userId' : IDL.Principal,
    'date' : Time,
    'subscriptionPlan' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Subscription = IDL.Record({
    'status' : IDL.Text,
    'userId' : IDL.Principal,
    'plan' : IDL.Text,
    'isActive' : IDL.Bool,
    'billingCycle' : IDL.Text,
    'startDate' : Time,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'weight' : IDL.Float64,
    'height' : IDL.Float64,
    'activityLevel' : IDL.Text,
    'fitnessGoal' : IDL.Text,
    'dietaryPreferences' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'isOnboardingCompleted' : IDL.Bool,
    'gender' : IDL.Text,
    'allergies' : IDL.Vec(IDL.Text),
  });
  const ProgressEntry = IDL.Record({ 'value' : IDL.Float64, 'date' : Time });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'notificationType' : IDL.Text,
    'read' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDailyOrder' : IDL.Func([DailyMealOrder], [IDL.Nat], []),
    'addMeal' : IDL.Func([Meal], [IDL.Nat], []),
    'addPaymentRecord' : IDL.Func([PaymentRecord], [IDL.Nat], []),
    'addProgressEntry' : IDL.Func([IDL.Float64], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMeal' : IDL.Func([IDL.Nat], [], []),
    'getAllMeals' : IDL.Func([], [IDL.Vec(Meal)], ['query']),
    'getCallerSubscription' : IDL.Func([], [IDL.Opt(Subscription)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyOrder' : IDL.Func([IDL.Nat], [IDL.Opt(DailyMealOrder)], ['query']),
    'getMeal' : IDL.Func([IDL.Nat], [IDL.Opt(Meal)], ['query']),
    'getOrdersByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DailyMealOrder)],
        ['query'],
      ),
    'getPaymentsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PaymentRecord)],
        ['query'],
      ),
    'getProgressEntries' : IDL.Func([], [IDL.Vec(ProgressEntry)], ['query']),
    'getUserId' : IDL.Func([], [IDL.Principal], ['query']),
    'getUserNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSubscription' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(Subscription)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
    'saveCallerSubscription' : IDL.Func([Subscription], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendNotification' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text], [], []),
    'updateDailyOrder' : IDL.Func([IDL.Nat, DailyMealOrder], [], []),
    'updateMeal' : IDL.Func([IDL.Nat, Meal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };