/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyMealOrder {
  'id' : bigint,
  'status' : string,
  'deliveryAddress' : string,
  'userId' : Principal,
  'date' : Time,
  'skip' : boolean,
  'deliveryTime' : bigint,
  'selectedMeals' : Array<bigint>,
}
export interface Meal {
  'id' : bigint,
  'fat' : bigint,
  'carbs' : bigint,
  'calories' : bigint,
  'name' : string,
  'tags' : Array<string>,
  'description' : string,
  'imageUrl' : string,
  'nutritionistApproved' : boolean,
  'allergens' : Array<string>,
  'protein' : bigint,
}
export interface Notification {
  'id' : bigint,
  'userId' : Principal,
  'notificationType' : string,
  'read' : boolean,
  'message' : string,
  'timestamp' : Time,
}
export interface PaymentRecord {
  'id' : bigint,
  'status' : string,
  'method' : string,
  'userId' : Principal,
  'date' : Time,
  'subscriptionPlan' : string,
  'amount' : bigint,
}
export interface ProgressEntry { 'value' : number, 'date' : Time }
export interface Subscription {
  'status' : string,
  'userId' : Principal,
  'plan' : string,
  'isActive' : boolean,
  'billingCycle' : string,
  'startDate' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'age' : bigint,
  'weight' : number,
  'height' : number,
  'activityLevel' : string,
  'fitnessGoal' : string,
  'dietaryPreferences' : Array<string>,
  'name' : string,
  'isOnboardingCompleted' : boolean,
  'gender' : string,
  'allergies' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDailyOrder' : ActorMethod<[DailyMealOrder], bigint>,
  'addMeal' : ActorMethod<[Meal], bigint>,
  'addPaymentRecord' : ActorMethod<[PaymentRecord], bigint>,
  'addProgressEntry' : ActorMethod<[number], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteMeal' : ActorMethod<[bigint], undefined>,
  'getAllMeals' : ActorMethod<[], Array<Meal>>,
  'getCallerSubscription' : ActorMethod<[], [] | [Subscription]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyOrder' : ActorMethod<[bigint], [] | [DailyMealOrder]>,
  'getMeal' : ActorMethod<[bigint], [] | [Meal]>,
  'getOrdersByUser' : ActorMethod<[Principal], Array<DailyMealOrder>>,
  'getPaymentsByUser' : ActorMethod<[Principal], Array<PaymentRecord>>,
  'getProgressEntries' : ActorMethod<[], Array<ProgressEntry>>,
  'getUserId' : ActorMethod<[], Principal>,
  'getUserNotifications' : ActorMethod<[], Array<Notification>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSubscription' : ActorMethod<[Principal], [] | [Subscription]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markNotificationAsRead' : ActorMethod<[bigint], undefined>,
  'saveCallerSubscription' : ActorMethod<[Subscription], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendNotification' : ActorMethod<[Principal, string, string], undefined>,
  'updateDailyOrder' : ActorMethod<[bigint, DailyMealOrder], undefined>,
  'updateMeal' : ActorMethod<[bigint, Meal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];